/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import controllers.EmpleadosController;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;

/**
 *
 * @author Usuario
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setControllers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuRegistrar = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jdesktopPaneLayout = new javax.swing.GroupLayout(jdesktopPane);
        jdesktopPane.setLayout(jdesktopPaneLayout);
        jdesktopPaneLayout.setHorizontalGroup(
            jdesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        jdesktopPaneLayout.setVerticalGroup(
            jdesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        getContentPane().add(jdesktopPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Empleados");

        menuRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/iconfinder_folder_job_seeker_employee_unemployee_work_2620522 (1).png"))); // NOI18N
        menuRegistrar.setText("Registrar empleados");
        jMenu1.add(menuRegistrar);

        menuEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/iconfinder_cv_job_seeker_employee_unemployee_work_2620524.png"))); // NOI18N
        menuEditar.setText("Editar empleado");
        jMenu1.add(menuEditar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public JDesktopPane getDesktopPane() {
        return jdesktopPane;
    }
    
    public void setControllers(){
        ec = new EmpleadosController(this);
        menuRegistrar.addActionListener(ec);  
    }

    public JMenuItem getMenuRegistrar() {
        return menuRegistrar;
    }
    
    
    
    private EmpleadosController ec;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdesktopPane;
    private javax.swing.JMenuItem menuEditar;
    private javax.swing.JMenuItem menuRegistrar;
    // End of variables declaration//GEN-END:variables
}
